### ISSUE TITLE
How to choose package scope ?

### ISSUE THREAD

**Issue by mahmoudhanafy** [databricks/sbt-spark-package#19]
I want to choose some packages as `provided`, others as `test` and others as `package`.
How to do this ?

**Comment by mahmoudhanafy** [comment]
@brkyvz Any Help ?

**Comment by brkyvz** [comment]
Hi @mahmoudhanafy , `spDependencies` is a convenience method for including packages. If you like, you may directly add the packages to `libraryDependencies` and add the scope there. `spDependencies` does not support scoping.

**Comment by mahmoudhanafy** [comment]
Thanks @brkyvz What about doing this with Spark components ? Can I do this using `sparkComponents` ?

**Comment by brkyvz** [comment]
@mahmoudhanafy The spark components are automatically "provided". They don't accept scoping either.
