### ISSUE TITLE
Local shared repository

### ISSUE THREAD

**Issue by huangjs** [databricks/sbt-spark-package#2]
How can I setup a shared repository for spark packages, for managing non-open-sourced packages we build internally?

Jianshi

**Comment by brkyvz** [comment]
Hi,
I'm not sure if I understood your question correctly, but I'll give it a try. The Spark Packages repository is a maven repository on Bintray. You can set up a private repo on Bintray, or a host of your choice and add that repository as a resolver in your build.sbt (as we do to add the Spark Package repo [here](https://github.com/databricks/sbt-spark-package/blob/eb823d6d3c9fd642334b886103b57de14e00acbd/src/main/scala/sbtsparkpackage/SparkPackagePlugin.scala#L182) ). 

Burak

**Comment by huangjs** [comment]
I see. Then i can just publish to our local nexus. Just wondering how it would package python code for distribution.

Jianshi

**Comment by brkyvz** [comment]
spPackage packages the python code in the root directory of the jar (in addition to the Java/Scala class files). When the jar is added to the sys.path or PYTHONPATH, python codes should run without a problem.

Burak

**Comment by huangjs** [comment]
Ah it's in the jar. I see. Thanks for the explanation. Would you recommend
using it for all Spark apps? As it handles python by default which saves
people some configurations. :)

Jianshi

On Sun, Mar 15, 2015 at 3:43 AM, Burak Yavuz <notifications@github.com>
wrote:

> spPackage packages the python code in the root directory of the jar (in
> addition to the Java/Scala class files). When the jar is added to the
> sys.path or PYTHONPATH, python codes should run without a problem.
>
> Burak
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/databricks/sbt-spark-package/issues/2#issuecomment-80690646>
> .
>



-- 
Jianshi Huang

LinkedIn: jianshi
Twitter: @jshuang
Github & Blog: http://huangjs.github.com/

**Comment by brkyvz** [comment]
Most certainly!

Burak
