### ISSUE TITLE
sbt-spark-package does not follow redirects

### ISSUE THREAD

**Issue by sadikovi** [databricks/sbt-spark-package#22]
It looks like `sbt-spark-package` does not follow redirects.
URL http://spark-packages.org/api/submit-package returns HTTP 302 and reports it as an error. 1ee3cf2994c46f50d77683a822510c3586059213 updated to https, and older package versions (at least 0.2.3) seem to fail with error.

I am using 0.2.3, and get this:
```
[info] Packaging /developer/spark-netflow/target/scala-2.11/spark-netflow_2.11-1.1.0.jar ...
[info] Done packaging.

Zip File created at: /developer/spark-netflow/target/spark-netflow-1.1.0-s_2.11.zip

ERROR: 302 - 
[success] Total time: 52 s, completed 26/06/2016 7:29:06 PM
```

Solvable by upgrading the package to `0.2.4`.

**Comment by sadikovi** [comment]
@brkyvz Can you have a look at this? Thanks.

**Comment by sadikovi** [comment]
Minor thing, it looks like URL in success message has not been updated - `http://spark-packages.org/staging?id=1261`, should be `https`.

**Comment by brkyvz** [comment]
Thank you for reporting this! Please use 0.2.4 and above from now on.
Thanks,
Burak
On Jun 26, 2016 12:47 AM, "Jony" <notifications@github.com> wrote:
>
> Minor thing, it looks like URL in success message has not been updated -
http://spark-packages.org/staging?id=1261, should be https.

**Comment by sadikovi** [comment]
@brkyvz thank you. Yeah, I updated version.
