### ISSUE TITLE
Unresolved dependency commons

### ISSUE THREAD

**Issue by rvesse** [databricks/sbt-spark-package#6]
When trying to build a Spark plugin using this plugin I receive the following error:

```
[warn] 	Note: Unresolved dependencies path:
[warn] 		commons-codec:commons-codec:1.8
[warn] 		  +- org.apache.directory.studio:org.apache.commons.codec:1.8
[warn] 		  +- org.spark-packages:sbt-spark-package:0.2.1 (sbtVersion=0.13, scalaVersion=2.10) (/Users/rvesse/Documents/Work/Code/spark-rdf/project/plugins.sbt#L5-6)
[warn] 		  +- default:spark-rdf-build:0.1-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10)
sbt.ResolveException: unresolved dependency: commons-codec#commons-codec;1.8: org.apache#apache;13!apache.pom(pom.original) origin location must be absolute: file:/Users/rvesse/.m2/repository/org/apache/apache/13/apache-13.pom
```

My `build.sbt` is a simple build file generated by the Databricks [spark-package](https://github.com/databricks/spark-package-cmd-tool) tool and the `project/plugins.sbt` simply has the definition for this plugin as described in the ReadMe

Any ideas on how to solve this?

**Comment by rvesse** [comment]
Apparently this was some sort of corrupted Ivy 2 cache issue, deleting the `~/.ivy2/` directory entirely and relaunching SBT resolved the problem

**Comment by bigdataanalyst1** [comment]
Thanks a lot after delete  .ivy2  file my problem is resolved.

**Comment by bashokku** [comment]
Thank you very much . deleting the ~/.ivy2/ folder worked for me .

**Comment by gurugv-zz** [comment]
Or just the specific jars. For eg : 
for this error :  org.apache.avro#avro;1.7.6: org.apache.avro#avro;1.7.6!avro.pom(pom.original) origin location must be absolute: file:/Users/guruprasad.gv/.m2/repository/org/apache/avro/avro/1.7.6/avro-1.7.6.pom

just delete : 
rm -rf ~/.ivy2/cache/org.apache.avro
rm -rf ~/.ivy2/jars/org.apache.avro_avro-1.7.6.jar

**Comment by lppant** [comment]
Thanks a lot. Deleting the specific .ivy2 directory and relaunching sbt fixed the problem.

For example, if the error is: 
sbt.ResolveException: unresolved dependency: commons-codec#commons-codec;1.8: org.apache#apache;13!apache.pom(pom.original) origin location must be absolute: file:/Users/rvesse/.m2/repository/org/apache/apache/13/apache-13.pom

Then, just do:
rm -rf ~/.ivy2/cache/org.apache/apache

It will solve the problem.
